### PR TITLE
Use message component for exclusive form reply event

### LINKED ISSUE #152: WDK 1.2.0: BPMN Engine error when starting WDK with Conditional Branching & Loops SWADL
**WDK 1.2.0: BPMN Engine error when starting WDK with Conditional Branching & Loops SWADL**

### Steps to Reproduce:
1. WDK 1.2.0 & SWADL = (https://github.com/SymphonyPlatformSolutions/symphony-training-research-workflow/blob/chapter-7/workflows/research.swadl.yaml)

2. Trying to start the WDK bot - will result in a number of BPMN Engine errors.

### Expected Result:
WDK 1.2.0 is expected to start up with the SWADL for Conditional Branching & Loops being expected to work as it does in WDK 1.1.0

### Actual Result:
The WDK 1.2.0 does not start up correctly and has BPMN Engine error messages - leading to the SWADL not working or action.

### Environment:
WDK 1.2.0
SWADL = (https://github.com/SymphonyPlatformSolutions/symphony-training-research-workflow/blob/chapter-7/workflows/research.swadl.yaml)

### Additional Context:
The Chapter 7 SWADL (https://github.com/SymphonyPlatformSolutions/symphony-training-research-w...) from the WDK Course works in WDK 1.1.0 but does not work in WDK 1.2.0.
​
When starting up the WDK Bot produces this error.
​
```
2022-09-27 17:02:21.070 ERROR 7158 --- [   scheduling-1] org.camunda.bpm.engine.context           : ENGINE-16004 Exception while closing command context: ENGINE-09005 Could not parse BPMN process. Errors: 
* Invalid destination 'authoringForm' of sequence flow 'sequenceFlow_0e5cde2a-3746-4007-a84d-d28e728b2c06' | resource research-workflow.bpmn | line 166 | column 156
org.camunda.bpm.engine.ParseException: ENGINE-09005 Could not parse BPMN process. Errors: 
* Invalid destination 'authoringForm' of sequence flow 'sequenceFlow_0e5cde2a-3746-4007-a84d-d28e728b2c06' | resource research-workflow.bpmn | line 166 | column 156
```

### PR DESCRIPTION
**Pull request by yinan-symphony**
Revert back to the original solution for exclusive FormRepliedEvent. Using subprocess is too much complex to handle the form reply use cases we can have right now.

### Description
close #152 

### Dependencies
List the other pull requests that should be merged before/along this one.

### Checklist
- [ ] Referenced a ticket in the PR title or description
- [ ] Filled properly the description and dependencies, if any
- [ ] Unit/Integration tests updated or added
- [ ] Javadoc added or updated
- [ ] Updated the documentation in [docs folder](../docs)

### CODE REVIEW

File: workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java [hunk 1]
```diff
@@ -60,4 +60,8 @@ public boolean isConditional(String parentId) {
   public String getIfCondition(String parentId) {
     return this.ifConditions.get(parentId);
   }
+
+  public boolean isNotExclusiveFormReply() {
+    return getElementType() == WorkflowNodeType.FORM_REPLIED_EVENT && !getEvent().getFormReplied().getExclusive();
```
Comment (symphony-soufiane) [inline workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java:65]: Can this sometimes cause a NP? if getEvent().getFormReplied() is null for instance..

Comment (symphony-soufiane) [reply workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java:65]: I would call it isExclusiveFormReply() and check it returns false

File: workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java [hunk 2]
```diff
@@ -153,11 +152,12 @@ private Optional<String> retrieveCondition(ActivityCompletedEvent event, BaseAct
...
 
-  private void computeSignal(WorkflowDirectGraph directGraph, Event event, String eventNodeId, int activityIndex,
-      List<Activity> activities) {
+  private void computeSignal(int activityIndex, List<Activity> activities, String eventNodeId, Event event,
+      RelationalEvents onEvents, WorkflowDirectGraph directGraph) {
     WorkflowNode signalEvent = new WorkflowNode().id(eventNodeId).event(event);
     String activityId = activities.get(activityIndex).getActivity().getId();
-    if (isFormRepliedEvent(event)) {
+
+    if (isFormRepliedEvent(event) && !event.getFormReplied().getExclusive()) {
```
Comment (symphony-soufiane) [inline workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java:160]: can't WorkflowNode.isNotExclusiveFormReply() be used here?

File: workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java [hunk 3]
```diff
@@ -32,7 +32,7 @@ void buildWorkflowDirectGraph_approvalFlow() throws Exception {
     Workflow workflow = SwadlParser.fromYaml(getClass().getResourceAsStream("/graph/approval.swadl.yaml"));
     workflowDirectGraphBuilder = new WorkflowDirectGraphBuilder(workflow, eventMapper);
     WorkflowDirectGraph directGraph = workflowDirectGraphBuilder.build();
-    assertThat(directGraph.getDictionary()).hasSize(8);
+    assertThat(directGraph.getDictionary()).hasSize(9);
```
Comment (symphony-soufiane) [inline workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java:35]: what this change is related to?

File: workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java (hunk 1 above)
Comment (yinan-symphony) [reply workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java:65]: if the type is a form reply, getEvent().getFormReplied() won't be null.
I call it isNotExclusiveFormReply, it s because everywhere this function is called, it is to check the form to be not exclusive, so it is more convenient to not have "!" every time this is called.

File: workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java (hunk 2 above)
Comment (yinan-symphony) [reply workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java:160]: no, it was what i did at the beginning.
the reason is because here i am trying to build this workflow node, and we don't know yet which node type this node would be, you can see the signalEvent at L157, the L160 is actually to determine the event type, so later on in the process, we will use isNotExclusiveFormReploy() method.
I even tried to put the event null check inside  isNotExclusiveFormReploy() method, but it has NPE during the process.

File: workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java (hunk 3 above)
Comment (yinan-symphony) [reply workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java:35]: the default timeout node for FormRepliedEvent, which was not created in graph builder before when using subprocess.

File: workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java (hunk 1 above)
Comment (symphony-soufiane) [reply workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java:65]: Yes but if one day we want to check the form to be exclusive, we will call (!isNot..) and you read it (not is not exclusive..), it will be mind blowing ^^
